export interface Team {
  name: string;
  fifaRank: number;
  powerScore: number;
}

export const TEAMS: Team[] = [
  { name: "🇫🇷 France", fifaRank: 1, powerScore: 48 },
  { name: "🇪🇸 Spain", fifaRank: 2, powerScore: 47 },
  { name: "🇦🇷 Argentina", fifaRank: 3, powerScore: 46 },
  { name: "🏴󠁧󠁢󠁥󠁮󠁧󠁿 England", fifaRank: 4, powerScore: 45 },
  { name: "🇵🇹 Portugal", fifaRank: 5, powerScore: 44 },
  { name: "🇧🇷 Brazil", fifaRank: 6, powerScore: 43 },
  { name: "🇳🇱 Netherlands", fifaRank: 7, powerScore: 42 },
  { name: "🇲🇦 Morocco", fifaRank: 8, powerScore: 41 },
  { name: "🇧🇪 Belgium", fifaRank: 9, powerScore: 40 },
  { name: "🇩🇪 Germany", fifaRank: 10, powerScore: 39 },
  { name: "🇭🇷 Croatia", fifaRank: 11, powerScore: 38 },
  { name: "🇨🇴 Colombia", fifaRank: 13, powerScore: 37 },
  { name: "🇸🇳 Senegal", fifaRank: 14, powerScore: 36 },
  { name: "🇲🇽 Mexico", fifaRank: 15, powerScore: 35 },
  { name: "🇺🇸 United States", fifaRank: 16, powerScore: 34 },
  { name: "🇺🇾 Uruguay", fifaRank: 17, powerScore: 33 },
  { name: "🇯🇵 Japan", fifaRank: 18, powerScore: 32 },
  { name: "🇨🇭 Switzerland", fifaRank: 19, powerScore: 31 },
  { name: "🇮🇷 Iran", fifaRank: 21, powerScore: 30 },
  { name: "🇹🇷 Türkiye", fifaRank: 22, powerScore: 29 },
  { name: "🇪🇨 Ecuador", fifaRank: 23, powerScore: 28 },
  { name: "🇦🇹 Austria", fifaRank: 24, powerScore: 27 },
  { name: "🇰🇷 South Korea", fifaRank: 25, powerScore: 26 },
  { name: "🇦🇺 Australia", fifaRank: 27, powerScore: 25 },
  { name: "🇨🇦 Canada", fifaRank: 30, powerScore: 24 },
  { name: "🇳🇴 Norway", fifaRank: 32, powerScore: 23 },
  { name: "🇪🇬 Egypt", fifaRank: 33, powerScore: 22 },
  { name: "🇩🇿 Algeria", fifaRank: 36, powerScore: 21 },
  { name: "🇸🇪 Sweden", fifaRank: 37, powerScore: 20 },
  { name: "🇵🇾 Paraguay", fifaRank: 38, powerScore: 19 },
  { name: "🇨🇮 Ivory Coast", fifaRank: 39, powerScore: 18 },
  { name: "🇨🇿 Czechia", fifaRank: 41, powerScore: 17 },
  { name: "🏴󠁧󠁢󠁳󠁣󠁴󠁿 Scotland", fifaRank: 43, powerScore: 16 },
  { name: "🇹🇳 Tunisia", fifaRank: 47, powerScore: 15 },
  { name: "🇵🇦 Panama", fifaRank: 51, powerScore: 14 },
  { name: "🇶🇦 Qatar", fifaRank: 53, powerScore: 13 },
  { name: "🇨🇩 DR Congo", fifaRank: 55, powerScore: 12 },
  { name: "🇮🇶 Iraq", fifaRank: 56, powerScore: 11 },
  { name: "🇺🇿 Uzbekistan", fifaRank: 57, powerScore: 10 },
  { name: "🇸🇦 Saudi Arabia", fifaRank: 58, powerScore: 9 },
  { name: "🇿🇦 South Africa", fifaRank: 60, powerScore: 8 },
  { name: "🇯🇴 Jordan", fifaRank: 64, powerScore: 7 },
  { name: "🇨🇻 Cape Verde", fifaRank: 70, powerScore: 6 },
  { name: "🇧🇦 Bosnia and Herzegovina", fifaRank: 71, powerScore: 5 },
  { name: "🇬🇭 Ghana", fifaRank: 73, powerScore: 4 },
  { name: "🇭🇹 Haiti", fifaRank: 79, powerScore: 3 },
  { name: "🇨🇼 Curacao", fifaRank: 81, powerScore: 2 },
  { name: "🇳🇿 New Zealand", fifaRank: 88, powerScore: 1 }
];
